# Generated by Django 4.2.2 on 2023-10-01 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bc_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MysteryShoppingOverview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "shopper_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("mobile", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("gender", models.CharField(blank=True, max_length=200, null=True)),
                ("start_time", models.TimeField(blank=True, max_length=200, null=True)),
                ("end_time", models.TimeField(blank=True, max_length=200, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "cost_of_service",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "paid_in_cash",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "payment_mode",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "amount_redeemed",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "contact_number_reached_for_appointment",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "auditor_action_reviewed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "om_action_reviewed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "service_availed_1",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "service_availed_2",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "service_availed_3",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.userprofile",
                    ),
                ),
                (
                    "auditor_access_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="auditor_access_to",
                        to="bc_app.userprofile",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "month_of_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bc_app.monthaudit",
                    ),
                ),
                (
                    "service_agent_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_agent_1",
                        to="bc_app.userprofile",
                    ),
                ),
                (
                    "service_agent_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_agent_2",
                        to="bc_app.userprofile",
                    ),
                ),
                (
                    "service_agent_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_agent_3",
                        to="bc_app.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MysteryShoppingImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("image", models.FileField(blank=True, null=True, upload_to="media")),
                (
                    "mystery_shopping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mystery_shopping.mysteryshoppingoverview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MysteryShoppingDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "compliance_dropdown",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "client_journey",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("kra", models.CharField(blank=True, max_length=200, null=True)),
                ("process", models.CharField(blank=True, max_length=200, null=True)),
                ("checklist", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "relative_gaps_found",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "audit_status",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "service_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "minimum_person_responsible",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "mystery_shopping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mystery_shopping.mysteryshoppingoverview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MysteryChecklistPersonResponsible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kra", models.CharField(blank=True, max_length=200, null=True)),
                ("compliance", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "compliance_category",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "compliance_category_percentage",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("comment_for_auditor", models.TextField(blank=True, null=True)),
                (
                    "action_taken_by_outlet_manager",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status_by_om",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("remark_by_om", models.TextField(blank=True, null=True)),
                (
                    "action_taken_by_management",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("remark_by_management", models.TextField(blank=True, null=True)),
                (
                    "expected_dept_intervene",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("remark_by_department", models.TextField(blank=True, null=True)),
                (
                    "status_by_department",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "is_important",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "action_status",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "mystery_checklist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mystery_shopping.mysteryshoppingdetail",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bc_app.userprofile",
                    ),
                ),
            ],
        ),
    ]
