# Generated by Django 4.2.2 on 2023-08-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0009_remove_centralaccess_audit_and_more"),
        ("mystery_shopping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysteryshoppingoverview",
            name="auditor_access_to",
            field=models.ManyToManyField(
                blank=True, related_name="auditor_access_to", to="bc_app.userprofile"
            ),
        ),
    ]
