# Generated by Django 4.2.2 on 2023-08-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0009_remove_centralaccess_audit_and_more"),
        (
            "mystery_shopping",
            "0003_alter_mysteryshoppingdetail_month_of_audit_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="staff",
        ),
        migrations.AddField(
            model_name="mysteryshoppingdetail",
            name="staff",
            field=models.ManyToManyField(
                blank=True, to="bc_app.extendedzenotiemployeesdata"
            ),
        ),
    ]
