# Generated by Django 4.2.2 on 2023-08-29 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mystery_shopping", "0005_alter_mysteryshoppingdetail_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="MysteryChecklistPersonResponsible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compliance", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "compliance_category",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "compliance_category_percentage",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "mystery_checklist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mystery_shopping.mysteryshoppingdetail",
                    ),
                ),
            ],
        ),
    ]
