# Generated by Django 4.2.2 on 2023-08-30 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0009_remove_centralaccess_audit_and_more"),
        ("mystery_shopping", "0009_remove_mysteryshoppingdetail_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mysteryshoppingoverview",
            name="service_agent_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_agent_1",
                to="bc_app.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="mysteryshoppingoverview",
            name="service_agent_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_agent_2",
                to="bc_app.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="mysteryshoppingoverview",
            name="service_agent_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_agent_3",
                to="bc_app.userprofile",
            ),
        ),
    ]
