# Generated by Django 4.2.2 on 2023-08-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mystery_shopping",
            "0011_remove_mysteryshoppingdetail_service_availed_1_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="date",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="month_of_audit",
        ),
    ]
