# Generated by Django 4.2.2 on 2023-08-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mystery_shopping", "0012_remove_mysteryshoppingdetail_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="center",
        ),
    ]
