# Generated by Django 4.2.2 on 2023-08-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mystery_shopping", "0014_mysterychecklistpersonresponsible_service_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mysteryshoppingimages",
            name="center",
        ),
    ]
