# Generated by Django 4.2.2 on 2023-09-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mystery_shopping", "0016_remove_mysteryshoppingdetail_remark_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="action_taken_by_management",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="action_taken_by_outlet_manager",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="audit_status",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="comment_for_auditor",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="compliance",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="compliance_category",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="compliance_category_percentage",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="expected_dept_intervene",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="is_important",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="relative_gaps_found",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="remark_by_department",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="remark_by_management",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="remark_by_om",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="service_number",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="status_by_department",
        ),
        migrations.RemoveField(
            model_name="mysteryshoppingdetail",
            name="status_by_om",
        ),
        migrations.AddField(
            model_name="mysterychecklistpersonresponsible",
            name="action_taken_by_management",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mysterychecklistpersonresponsible",
            name="action_taken_by_outlet_manager",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mysterychecklistpersonresponsible",
            name="audit_status",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mysterychecklistpersonresponsible",
            name="comment_for_auditor",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mysterychecklistpersonresponsible",
            name="expected_dept_intervene",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mysterychecklistpersonresponsible",
            name="is_important",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="mysterychecklistpersonresponsible",
            name="relative_gaps_found",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="mysterychecklistpersonresponsible",
            name="remark_by_department",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mysterychecklistpersonresponsible",
            name="remark_by_management",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mysterychecklistpersonresponsible",
            name="remark_by_om",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mysterychecklistpersonresponsible",
            name="status_by_department",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mysterychecklistpersonresponsible",
            name="status_by_om",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
