# Generated by Django 4.2.2 on 2023-09-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mystery_shopping",
            "0017_remove_mysteryshoppingdetail_action_taken_by_management_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mysterychecklistpersonresponsible",
            name="audit_status",
        ),
        migrations.RemoveField(
            model_name="mysterychecklistpersonresponsible",
            name="relative_gaps_found",
        ),
        migrations.AddField(
            model_name="mysteryshoppingdetail",
            name="audit_status",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mysteryshoppingdetail",
            name="relative_gaps_found",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="mysteryshoppingdetail",
            name="service_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
