# Generated by Django 4.2.2 on 2023-09-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mystery_shopping",
            "0018_remove_mysterychecklistpersonresponsible_audit_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mysterychecklistpersonresponsible",
            name="service_number",
        ),
        migrations.AddField(
            model_name="mysterychecklistpersonresponsible",
            name="action_status",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
