# Generated by Django 4.2.2 on 2023-09-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mystery_shopping", "0020_mysterychecklistpersonresponsible_kra"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysteryshoppingdetail",
            name="minimum_person_responsible",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
