# Generated by Django 4.2.2 on 2023-06-21 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssociatedRoleOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExtendedZenotiCenterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "closing_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "center_status",
                    models.CharField(
                        blank=True,
                        choices=[("Active", "Active"), ("InActive", "InActive")],
                        default="Active",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExtendedZenotiEmployeesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "office_start_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "office_end_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "is_manager",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "associated_center",
                    models.ManyToManyField(
                        blank=True, to="bc_app.extendedzenoticenterdata"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SecretKeyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SectionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_super_admin",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, default="profile1.jpg", null=True, upload_to=""
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "user_type",
                    models.CharField(
                        blank=True,
                        choices=[("Zenoti", "Zenoti"), ("Non Zenoti", "Non Zenoti")],
                        max_length=100,
                    ),
                ),
                (
                    "user_status",
                    models.CharField(
                        blank=True,
                        choices=[("Active", "Active"), ("InActive", "InActive")],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "roster_access",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("date_of_joining", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WeekOffOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZenotiCentersData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zenoticenterId",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("address_1", models.CharField(blank=True, max_length=500, null=True)),
                ("address_2", models.CharField(blank=True, max_length=500, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZenotiEmployeesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "employee_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=500, null=True)),
                ("job_info", models.CharField(blank=True, max_length=500, null=True)),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.userprofile",
                    ),
                ),
                (
                    "zenoti_center",
                    models.ManyToManyField(blank=True, to="bc_app.zenoticentersdata"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_type_name",
            field=models.ManyToManyField(to="bc_app.usertypes"),
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("start_time", models.TimeField(blank=True, max_length=100, null=True)),
                ("end_time", models.TimeField(blank=True, max_length=100, null=True)),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.operationoption",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.sectionoption",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtendedZenotiEmployeesLeaveData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_from_date", models.DateField(blank=True, null=True)),
                ("leave_to_date", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Approved", "Approved"),
                            ("Pending", "Pending"),
                            ("Rejected", "Rejected"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "zenoti_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenotiemployeesdata",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="extendedzenotiemployeesdata",
            name="associated_role",
            field=models.ManyToManyField(blank=True, to="bc_app.position"),
        ),
        migrations.AddField(
            model_name="extendedzenotiemployeesdata",
            name="week_off",
            field=models.ManyToManyField(blank=True, to="bc_app.weekoffoptions"),
        ),
        migrations.AddField(
            model_name="extendedzenotiemployeesdata",
            name="zenoti_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bc_app.zenotiemployeesdata",
            ),
        ),
        migrations.AddField(
            model_name="extendedzenoticenterdata",
            name="closed_on",
            field=models.ManyToManyField(blank=True, to="bc_app.weekoffoptions"),
        ),
        migrations.AddField(
            model_name="extendedzenoticenterdata",
            name="position",
            field=models.ManyToManyField(blank=True, to="bc_app.position"),
        ),
        migrations.AddField(
            model_name="extendedzenoticenterdata",
            name="zenoti_data",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bc_app.zenoticentersdata",
            ),
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.CharField(blank=True, max_length=200, null=True)),
                ("sentence", models.TextField(blank=True, null=True)),
                ("data", models.TextField(blank=True, null=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeScheduler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Available", "Available"),
                            ("Week Off", "Week Off"),
                            ("Leave Request", "Leave Request"),
                            ("Leave Approved", "Leave Approved"),
                            ("Unplanned Leave", "Unplanned Leave"),
                            ("Training/Meeting", "Training/Meeting"),
                            ("Floating Resource", "Floating Resource"),
                            ("Internal Transfer", "Internal Transfer"),
                            ("Exit", "Exit"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("remark", models.CharField(blank=True, max_length=500, null=True)),
                ("appoint_date", models.DateField(blank=True, null=True)),
                (
                    "office_start_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "office_end_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "associated_role",
                    models.ManyToManyField(blank=True, to="bc_app.position"),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenotiemployeesdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appoint_date", models.DateField(blank=True, null=True)),
                (
                    "office_start_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "office_end_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "associated_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.position",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenotiemployeesdata",
                    ),
                ),
            ],
        ),
    ]
