# Generated by Django 4.2.2 on 2023-10-01 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssociatedRoleOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audit_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ExtendedZenotiCenterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "closing_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "center_status",
                    models.CharField(
                        blank=True,
                        choices=[("Active", "Active"), ("InActive", "InActive")],
                        default="Active",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExtendedZenotiEmployeesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "office_start_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "office_end_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "is_manager",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "associated_center",
                    models.ManyToManyField(
                        blank=True, to="bc_app.extendedzenoticenterdata"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KRA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kra", models.CharField(blank=True, max_length=100, null=True)),
                ("start_time", models.TimeField(blank=True, max_length=100, null=True)),
                ("end_time", models.TimeField(blank=True, max_length=100, null=True)),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="KRACategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="KRADesignation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonthAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SecretKeyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SlrAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "auditor_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "trainer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("date_of_audit", models.DateField(blank=True, null=True)),
                (
                    "auditor_action_reviewed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "om_action_reviewed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_super_admin",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_audit_admin",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, default="profile1.jpg", null=True, upload_to=""
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "user_type",
                    models.CharField(
                        blank=True,
                        choices=[("Zenoti", "Zenoti"), ("Non Zenoti", "Non Zenoti")],
                        max_length=100,
                    ),
                ),
                (
                    "user_status",
                    models.CharField(
                        blank=True,
                        choices=[("Active", "Active"), ("InActive", "InActive")],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "roster_access",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "office_start_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "office_end_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "is_manager",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("date_of_joining", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "associated_center",
                    models.ManyToManyField(
                        blank=True, to="bc_app.extendedzenoticenterdata"
                    ),
                ),
                ("associated_kra", models.ManyToManyField(blank=True, to="bc_app.kra")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WeekOffOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZenotiCentersData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zenoticenterId",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("address_1", models.CharField(blank=True, max_length=500, null=True)),
                ("address_2", models.CharField(blank=True, max_length=500, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZenotiEmployeesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "employee_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=500, null=True)),
                ("job_info", models.CharField(blank=True, max_length=500, null=True)),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.userprofile",
                    ),
                ),
                (
                    "zenoti_center",
                    models.ManyToManyField(blank=True, to="bc_app.zenoticentersdata"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_type_name",
            field=models.ManyToManyField(blank=True, to="bc_app.usertypes"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="week_off",
            field=models.ManyToManyField(blank=True, to="bc_app.weekoffoptions"),
        ),
        migrations.CreateModel(
            name="SlrSalonImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("image", models.FileField(blank=True, null=True, upload_to="media")),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "slr_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.slraudit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SLRSalonAuditAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auditors",
                    models.ManyToManyField(blank=True, to="bc_app.userprofile"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlrDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "compliance_dropdown",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("audited_by", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "kra_responsible",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("protocol", models.CharField(blank=True, max_length=200, null=True)),
                ("checklist", models.TextField(blank=True, null=True)),
                ("methodology", models.TextField(blank=True, null=True)),
                ("compliance", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "compliance_category",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "compliance_category_percentage",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("audit_remarks", models.TextField(blank=True, null=True)),
                (
                    "audit_status",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("comment_for_auditor", models.TextField(blank=True, null=True)),
                (
                    "action_taken_by_outlet_manager",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status_by_om",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("remark_by_om", models.TextField(blank=True, null=True)),
                (
                    "action_taken_by_management",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("remark_by_management", models.TextField(blank=True, null=True)),
                (
                    "expected_dept_intervene",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("remark_by_department", models.TextField(blank=True, null=True)),
                (
                    "status_by_department",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "month_of_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bc_app.monthaudit",
                    ),
                ),
                (
                    "person_responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bc_app.extendedzenotiemployeesdata",
                    ),
                ),
                (
                    "slr_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.slraudit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="slraudit",
            name="access_given_to",
            field=models.ManyToManyField(
                blank=True, related_name="access_given_to", to="bc_app.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="slraudit",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bc_app.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="slraudit",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bc_app.extendedzenoticenterdata",
            ),
        ),
        migrations.AddField(
            model_name="slraudit",
            name="month_of_audit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bc_app.monthaudit",
            ),
        ),
        migrations.AddField(
            model_name="kra",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bc_app.kradesignation",
            ),
        ),
        migrations.AddField(
            model_name="extendedzenotiemployeesdata",
            name="associated_kra",
            field=models.ManyToManyField(blank=True, to="bc_app.kra"),
        ),
        migrations.AddField(
            model_name="extendedzenotiemployeesdata",
            name="week_off",
            field=models.ManyToManyField(blank=True, to="bc_app.weekoffoptions"),
        ),
        migrations.AddField(
            model_name="extendedzenotiemployeesdata",
            name="zenoti_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bc_app.zenotiemployeesdata",
            ),
        ),
        migrations.AddField(
            model_name="extendedzenoticenterdata",
            name="associated_kra",
            field=models.ManyToManyField(blank=True, to="bc_app.kra"),
        ),
        migrations.AddField(
            model_name="extendedzenoticenterdata",
            name="closed_on",
            field=models.ManyToManyField(blank=True, to="bc_app.weekoffoptions"),
        ),
        migrations.AddField(
            model_name="extendedzenoticenterdata",
            name="zenoti_data",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bc_app.zenoticentersdata",
            ),
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.CharField(blank=True, max_length=200, null=True)),
                ("sentence", models.TextField(blank=True, null=True)),
                ("data", models.TextField(blank=True, null=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeesLeaveData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_from_date", models.DateField(blank=True, null=True)),
                ("leave_to_date", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Approved", "Approved"),
                            ("Pending", "Pending"),
                            ("Rejected", "Rejected"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeScheduler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Available", "Available"),
                            ("Week Off", "Week Off"),
                            ("Leave Request", "Leave Request"),
                            ("Leave Approved", "Leave Approved"),
                            ("Unplanned Leave", "Unplanned Leave"),
                            ("Training/Meeting", "Training/Meeting"),
                            ("Floating Resource", "Floating Resource"),
                            ("Internal Transfer", "Internal Transfer"),
                            ("Exit", "Exit"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("remark", models.CharField(blank=True, max_length=500, null=True)),
                ("appoint_date", models.DateField(blank=True, null=True)),
                (
                    "office_start_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "office_end_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("associated_kra", models.ManyToManyField(blank=True, to="bc_app.kra")),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appoint_date", models.DateField(blank=True, null=True)),
                (
                    "office_start_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "office_end_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "associated_kra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.kra",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CentralAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audit", models.ManyToManyField(blank=True, to="bc_app.audittypes")),
                (
                    "audit_reviewer",
                    models.ManyToManyField(
                        blank=True,
                        related_name="audit_reviewer_of",
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "auditor",
                    models.ManyToManyField(
                        blank=True,
                        related_name="auditor_of",
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "project_owner",
                    models.ManyToManyField(
                        blank=True,
                        related_name="project_manager_of",
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "senior_management",
                    models.ManyToManyField(
                        blank=True,
                        related_name="senior_management_of",
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                ("staff", models.ManyToManyField(blank=True, to="bc_app.userprofile")),
            ],
        ),
        migrations.CreateModel(
            name="AuditAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit",
                    models.CharField(
                        blank=True,
                        choices=[("SLR Salon", "SLR Salon")],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "edit_access",
                    models.ManyToManyField(blank=True, to="bc_app.userprofile"),
                ),
                (
                    "user_type_name",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.usertypes",
                    ),
                ),
                (
                    "view_access",
                    models.ManyToManyField(
                        blank=True,
                        related_name="view_access_user",
                        to="bc_app.userprofile",
                    ),
                ),
            ],
        ),
    ]
