# Generated by Django 4.2.2 on 2023-06-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_type_name",
            field=models.ManyToManyField(blank=True, to="bc_app.usertypes"),
        ),
    ]
