# Generated by Django 4.2.2 on 2023-10-01 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0002_remove_employeeroster_associated_kra_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KRA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kra", models.CharField(blank=True, max_length=100, null=True)),
                ("start_time", models.TimeField(blank=True, max_length=100, null=True)),
                ("end_time", models.TimeField(blank=True, max_length=100, null=True)),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.kradesignation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employeeroster",
            name="associated_kra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bc_app.kra",
            ),
        ),
        migrations.AddField(
            model_name="employeescheduler",
            name="associated_kra",
            field=models.ManyToManyField(blank=True, to="bc_app.kra"),
        ),
        migrations.AddField(
            model_name="extendedzenoticenterdata",
            name="associated_kra",
            field=models.ManyToManyField(blank=True, to="bc_app.kra"),
        ),
        migrations.AddField(
            model_name="extendedzenotiemployeesdata",
            name="associated_kra",
            field=models.ManyToManyField(blank=True, to="bc_app.kra"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="associated_kra",
            field=models.ManyToManyField(blank=True, to="bc_app.kra"),
        ),
    ]
