# Generated by Django 4.2.2 on 2023-06-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0002_alter_userprofile_user_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SlrAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "auditor_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "trainer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("date_of_audit", models.DateField(blank=True, null=True)),
                (
                    "auditor_action_reviewed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "om_action_reviewed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.userprofile",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "month_of_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bc_app.monthaudit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlrSalonImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("image", models.FileField(blank=True, null=True, upload_to="media")),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "slr_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.slraudit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SLRSalonAuditAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auditors",
                    models.ManyToManyField(blank=True, to="bc_app.userprofile"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlrDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "compliance_dropdown",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("audited_by", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "kra_responsible",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("protocol", models.CharField(blank=True, max_length=200, null=True)),
                ("checklist", models.TextField(blank=True, null=True)),
                ("methodology", models.TextField(blank=True, null=True)),
                ("compliance", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "compliance_category",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "compliance_category_percentage",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("audit_remarks", models.TextField(blank=True, null=True)),
                (
                    "audit_status",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("comment_for_auditor", models.TextField(blank=True, null=True)),
                (
                    "action_taken_by_outlet_manager",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status_by_om",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("remark_by_om", models.TextField(blank=True, null=True)),
                (
                    "action_taken_by_management",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("remark_by_management", models.TextField(blank=True, null=True)),
                (
                    "expected_dept_intervene",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("remark_by_department", models.TextField(blank=True, null=True)),
                (
                    "status_by_department",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "month_of_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bc_app.monthaudit",
                    ),
                ),
                (
                    "person_responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bc_app.extendedzenotiemployeesdata",
                    ),
                ),
                (
                    "slr_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.slraudit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit",
                    models.CharField(
                        blank=True,
                        choices=[("SLR Salon", "SLR Salon")],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "edit_access",
                    models.ManyToManyField(blank=True, to="bc_app.userprofile"),
                ),
                (
                    "user_type_name",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.usertypes",
                    ),
                ),
                (
                    "view_access",
                    models.ManyToManyField(
                        blank=True,
                        related_name="view_access_user",
                        to="bc_app.userprofile",
                    ),
                ),
            ],
        ),
    ]
