# Generated by Django 4.2.2 on 2023-06-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0003_monthaudit_slraudit_slrsalonimages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slraudit",
            name="access_given_to",
            field=models.ManyToManyField(
                blank=True, related_name="access_given_to", to="bc_app.userprofile"
            ),
        ),
    ]
