# Generated by Django 4.2.2 on 2023-10-01 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0003_kra_employeeroster_associated_kra_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kradesignation",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bc_app.kracategory",
            ),
        ),
    ]
