# Generated by Django 4.2.2 on 2023-10-03 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0004_kradesignation_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extendedzenoticenterdata",
            name="associated_kra",
        ),
        migrations.CreateModel(
            name="CenterKra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "kra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bc_app.kra",
                    ),
                ),
            ],
        ),
    ]
