# Generated by Django 4.2.2 on 2023-06-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0004_slraudit_access_given_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_audit_admin",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
