# Generated by Django 4.2.2 on 2023-08-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0006_centralaccess"),
    ]

    operations = [
        migrations.RenameField(
            model_name="centralaccess",
            old_name="project_manager",
            new_name="project_owner",
        ),
    ]
