# Generated by Django 4.2.2 on 2023-10-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0006_centerkra_center"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="employeescheduler",
            name="associated_kra",
        ),
        migrations.RemoveField(
            model_name="employeescheduler",
            name="center",
        ),
        migrations.RemoveField(
            model_name="employeescheduler",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="errorlog",
            name="employee",
        ),
        migrations.DeleteModel(
            name="EmployeeRoster",
        ),
        migrations.DeleteModel(
            name="EmployeeScheduler",
        ),
        migrations.DeleteModel(
            name="ErrorLog",
        ),
    ]
