# Generated by Django 4.2.2 on 2023-08-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0007_rename_project_manager_centralaccess_project_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audit_type", models.CharField(max_length=100)),
            ],
        ),
    ]
