# Generated by Django 4.2.2 on 2023-10-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0008_alter_centerkra_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="centerkra",
            name="location",
        ),
    ]
