# Generated by Django 4.2.2 on 2023-08-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0008_audittypes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="centralaccess",
            name="audit",
        ),
        migrations.RemoveField(
            model_name="centralaccess",
            name="staff",
        ),
        migrations.AddField(
            model_name="centralaccess",
            name="audit",
            field=models.ManyToManyField(blank=True, to="bc_app.audittypes"),
        ),
        migrations.AddField(
            model_name="centralaccess",
            name="staff",
            field=models.ManyToManyField(blank=True, to="bc_app.userprofile"),
        ),
    ]
