# Generated by Django 4.2.2 on 2023-10-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0009_remove_centerkra_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="centerkra",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bc_app.location",
            ),
        ),
    ]
