# Generated by Django 4.2.2 on 2023-09-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0009_remove_centralaccess_audit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="added_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="associated_center",
            field=models.ManyToManyField(
                blank=True, to="bc_app.extendedzenoticenterdata"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="associated_role",
            field=models.ManyToManyField(blank=True, to="bc_app.position"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_manager",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="office_end_time",
            field=models.TimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="office_start_time",
            field=models.TimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="week_off",
            field=models.ManyToManyField(blank=True, to="bc_app.weekoffoptions"),
        ),
    ]
