# Generated by Django 4.2.2 on 2023-09-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bc_app",
            "0010_userprofile_added_date_userprofile_associated_center_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="added_date",
        ),
    ]
