# Generated by Django 4.2.2 on 2023-10-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0010_centerkra_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="associated_location",
            field=models.ManyToManyField(blank=True, to="bc_app.location"),
        ),
    ]
