# Generated by Django 4.2.2 on 2023-10-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0011_userprofile_associated_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="primary_kra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_kra",
                to="bc_app.kra",
            ),
        ),
    ]
