# Generated by Django 4.2.2 on 2023-10-04 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bc_app", "0007_location_remove_employeescheduler_associated_kra_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.CharField(blank=True, max_length=200, null=True)),
                ("sentence", models.TextField(blank=True, null=True)),
                ("data", models.TextField(blank=True, null=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeScheduler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Available", "Available"),
                            ("Week Off", "Week Off"),
                            ("Leave Request", "Leave Request"),
                            ("Leave Approved", "Leave Approved"),
                            ("Unplanned Leave", "Unplanned Leave"),
                            ("Training/Meeting", "Training/Meeting"),
                            ("Floating Resource", "Floating Resource"),
                            ("Internal Transfer", "Internal Transfer"),
                            ("Exit", "Exit"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("remark", models.CharField(blank=True, max_length=500, null=True)),
                ("appoint_date", models.DateField(blank=True, null=True)),
                (
                    "office_start_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "office_end_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "associated_role",
                    models.ManyToManyField(blank=True, to="bc_app.kra"),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenotiemployeesdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appoint_date", models.DateField(blank=True, null=True)),
                (
                    "office_start_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "office_end_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "associated_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.kra",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bc_app.extendedzenotiemployeesdata",
                    ),
                ),
            ],
        ),
    ]
