# Generated by Django 4.2.2 on 2023-10-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0011_userprofile_associated_location"),
        ("roster", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeroster",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bc_app.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="employeescheduler",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bc_app.userprofile",
            ),
        ),
    ]
