# Generated by Django 4.2.2 on 2023-10-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bc_app", "0011_userprofile_associated_location"),
        ("roster", "0004_employeeroster_associated_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeescheduler",
            name="associated_kra",
        ),
        migrations.AddField(
            model_name="employeescheduler",
            name="associated_kra",
            field=models.ManyToManyField(blank=True, to="bc_app.kra"),
        ),
    ]
